version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    image: backend:latest
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - application